name: CI
on:
  push:

jobs:
  jvm:
    strategy:
      fail-fast: true
      matrix:
        java: [11, 17]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: "openjdk@1.${{ matrix.java }}"
      - run: sbt Test/compile
